### ISSUE TITLE
Sticky Header at the top while allowing the content of the features module/page to scroll underneath it

### ISSUE THREAD

**Issue by hsn-ali** [VishwasSaini25/food-recipe-search#1]
Hi, hope your'e doing well,

Please assign it to me so that I can work on it if required!

![image](https://github.com/VishwasSaini25/food-recipe-search/assets/75776012/272a607a-52a9-466f-a330-422fc096a76f)

**Comment by VishwasSaini25** [comment]
Assigned, you can work on it!
